name: GitHub Build
on: [push]
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Installing dependencies
        run: sudo npm install
      - name: Run tests
        run: sudo npm test

